/**
 * Family B — Invoice and reconciliation. Episodes B1 and B2.
 */
import type { ScenarioDefinition } from "./schema.ts";
import { ITEMS, SUPPLIERS, LEDGER_OPENING, POLICY, atDay } from "./fixtures.ts";

const priorPeriodObjects = {
  purchaseOrders: {
    "PO-2201": {
      id: "PO-2201",
      supplierId: "SUP-MARWELL",
      lines: [{ itemId: "CLN-080", qty: 2, unitPriceMinor: 4100 }],
      status: "received" as const,
      note: "Prior-period order (settled cycle).",
      createdAtMinute: -28800,
      requestedDeliveryDay: -3,
      managerApproved: false,
      approvals: [],
      amendments: [],
      budgetCommittedMinor: 8200,
    },
  },
  deliveries: {
    "DV-870": {
      id: "DV-870",
      poId: "PO-2201",
      lines: [{ itemId: "CLN-080", qty: 2 }],
      status: "checked_in" as const,
      arrivedAtMinute: -25920,
      checkedInAtMinute: -25920,
      note: "Prior-period receipt.",
      carrierNote: "",
    },
  },
  invoices: {
    "INV-2035": {
      id: "INV-2035",
      invoiceNumber: "INV-2035",
      supplierId: "SUP-MARWELL",
      poId: "PO-2201",
      deliveryId: "DV-870",
      lines: [{ itemId: "CLN-080", qty: 2, unitPriceMinor: 4100 }],
      amountMinor: 8200,
      adjustedAmountMinor: null,
      currency: "CAD" as const,
      status: "approved" as const,
      dueDay: 12,
      receivedAtMinute: -25920,
      duplicateOfId: null,
      disputeReason: null,
      settlementTxnIds: [],
    },
  },
};

export const B1: ScenarioDefinition = {
  id: "B1",
  family: "invoice_reconciliation",
  version: "1.0.0",
  title: "Clean three-way match",
  brief: {
    role: "Operations Coordinator",
    company: "Northline Supply Co. (synthetic)",
    situation:
      "PO-2230 (Kettle: bolts ×6, cleaner ×2) is authorized. The delivery lands day 2 and the invoice day 3. " +
      "Match, approve and settle correctly. INV-2035 (prior period) is also open and due day 12.",
    objectives: [
      "Check in the delivery when it arrives",
      "Match the invoice to the PO and the delivery (three-way match)",
      "Approve and settle exactly the delivered value — once",
      "Update the reconciliation sheet and close TCK-105",
    ],
    guidance: [
      "Matching is only allowed against a recorded delivery (policy P3).",
      "Settlement happens once per invoice (policy P4) — payment runs are idempotent per invoice.",
      "Keep the reconciliation workbook consistent with the actual records.",
    ],
  },
  durationMinutes: atDay(14),
  policy: { ...POLICY, helpPolicy: { maxHelpRequests: 3, fatalBeyond: false } },
  items: ITEMS,
  suppliers: SUPPLIERS,
  initial: {
    purchaseOrders: {
      "PO-2230": {
        id: "PO-2230",
        supplierId: "SUP-KETTLE",
        lines: [
          { itemId: "FST-550", qty: 6, unitPriceMinor: 1850 },
          { itemId: "CLN-080", qty: 2, unitPriceMinor: 4300 },
        ],
        status: "authorized",
        note: "Restock order for stock replenishment.",
        createdAtMinute: -1440,
        requestedDeliveryDay: 2,
        managerApproved: true,
        approvals: [{ atMinute: -1440, approvedBy: "Dana Reyes (Operations Manager)" }],
        amendments: [],
        budgetCommittedMinor: 19700,
      },
      ...priorPeriodObjects.purchaseOrders,
    },
    deliveries: { ...priorPeriodObjects.deliveries },
    invoices: { ...priorPeriodObjects.invoices },
    ledgerOpening: LEDGER_OPENING,
    tickets: {
      "TCK-105": {
        id: "TCK-105",
        title: "Kettle restock — order-to-pay cycle",
        customer: "Internal (stock)",
        status: "in_progress",
        priority: "normal",
        dueDay: 12,
        notes: [{ atMinute: 0, text: "PO-2230 authorized; awaiting delivery and invoice." }],
        commitments: [],
      },
    },
    messages: [],
    workbooks: {
      "RECON-B1": {
        id: "RECON-B1",
        name: "three-way-match",
        cells: {
          A1: "Document",
          B1: "Reference",
          C1: "Amount (minor)",
          A2: "PO total",
          B2: "PO-2230",
          C2: 19700,
          A3: "Delivery value",
          B3: "DV-889",
          A4: "Invoice amount",
          B4: "INV-2041",
          A5: "Settlement",
          B5: "INV-2041",
          A7: "Variance",
          C7: { formula: "C2-C4" },
        },
        edits: [],
      },
    },
    workNotes: [],
    committedMinor: 27900,
  },
  scheduledEvents: [
    {
      id: "B1-delivery",
      fireAtMinute: atDay(2),
      kind: "delivery_arrival",
      payload: {
        poId: "PO-2230",
        deliveryId: "DV-889",
        lines: [
          { itemId: "FST-550", qty: 6 },
          { itemId: "CLN-080", qty: 2 },
        ],
        carrierNote: "Complete against PO-2230.",
      },
      fired: false,
    },
    {
      id: "B1-invoice",
      fireAtMinute: atDay(3),
      kind: "invoice_arrival",
      payload: {
        invoiceId: "INV-2041",
        invoiceNumber: "INV-2041",
        supplierId: "SUP-KETTLE",
        poId: "PO-2230",
        lines: [
          { itemId: "FST-550", qty: 6, unitPriceMinor: 1850 },
          { itemId: "CLN-080", qty: 2, unitPriceMinor: 4300 },
        ],
        amountMinor: 19700,
        currency: "CAD",
        dueDay: 33,
      },
      fired: false,
    },
  ],
  requirements: { lines: [], dueDay: 12 },
  requirementPredicates: [
    {
      id: "rp-paid",
      description: "INV-2041 settled",
      kind: "invoice_status",
      params: { invoiceId: "INV-2041", status: "paid" },
    },
    {
      id: "rp-exact",
      description: "INV-2041 settled for exactly the delivered value",
      kind: "settlement_amount_exact",
      params: { invoiceId: "INV-2041", amountMinor: 19700 },
    },
    {
      id: "rp-delivery",
      description: "DV-889 checked in",
      kind: "delivery_checked_in",
      params: { deliveryId: "DV-889" },
    },
  ],
  requiredUpdates: [
    {
      id: "ru-recon",
      description: "reconciliation workbook updated",
      kind: "workbook_edited",
      params: { workbookId: "RECON-B1" },
    },
    {
      id: "ru-ticket",
      description: "TCK-105 resolved or closed",
      kind: "ticket_status_min",
      params: { ticketId: "TCK-105", minStatus: "resolved" },
    },
    { id: "ru-submit", description: "work submitted", kind: "submission_present", params: {} },
  ],
  publicChecklist: [
    "Check in DV-889 when it arrives",
    "Match INV-2041 to PO-2230 and DV-889",
    "Approve the invoice at the delivered value",
    "Schedule and run payment exactly once",
    "Update the reconciliation sheet and resolve TCK-105",
    "Submit your work",
  ],
};

export const B2: ScenarioDefinition = {
  id: "B2",
  family: "invoice_reconciliation",
  version: "1.0.0",
  title: "Duplicate invoice and quantity discrepancy",
  brief: {
    role: "Operations Coordinator",
    company: "Northline Supply Co. (synthetic)",
    situation:
      "PO-2230 (Marwell: gloves ×8) is authorized. The delivery arrives short (6 of 8), the invoice bills 8 — " +
      "and two days later a second invoice for the same order and amount lands in the inbox.",
    objectives: [
      "Never settle undelivered goods (policy P5)",
      "Identify and flag the duplicate invoice (policy P6)",
      "Document the discrepancy with the supplier",
      "Keep TCK-106 and the records consistent",
    ],
    guidance: [
      "P5: settle delivered quantity only (short-pay with a note) and dispute the remainder — or hold settlement entirely.",
      "P6: a second invoice with the same supplier, reference and amount must be flagged as a suspected duplicate.",
      "You may ask for help, but policy questions here are answerable from the rules — repeated requests count against policy.",
    ],
  },
  durationMinutes: atDay(14),
  policy: { ...POLICY, helpPolicy: { maxHelpRequests: 2, fatalBeyond: true } },
  items: ITEMS,
  suppliers: SUPPLIERS,
  initial: {
    purchaseOrders: {
      "PO-2230": {
        id: "PO-2230",
        supplierId: "SUP-MARWELL",
        lines: [{ itemId: "GLV-100", qty: 8, unitPriceMinor: 2950 }],
        status: "authorized",
        note: "Gloves order for stock replenishment.",
        createdAtMinute: -1440,
        requestedDeliveryDay: 3,
        managerApproved: true,
        approvals: [{ atMinute: -1440, approvedBy: "Dana Reyes (Operations Manager)" }],
        amendments: [],
        budgetCommittedMinor: 23600,
      },
      ...priorPeriodObjects.purchaseOrders,
    },
    deliveries: { ...priorPeriodObjects.deliveries },
    invoices: { ...priorPeriodObjects.invoices },
    ledgerOpening: LEDGER_OPENING,
    tickets: {
      "TCK-106": {
        id: "TCK-106",
        title: "Marwell gloves order — billing watch",
        customer: "Internal (stock)",
        status: "in_progress",
        priority: "high",
        dueDay: 14,
        notes: [{ atMinute: 0, text: "PO-2230 authorized; watch the billing on this one." }],
        commitments: [],
      },
    },
    messages: [],
    workbooks: {
      "RECON-B2": {
        id: "RECON-B2",
        name: "discrepancy-worksheet",
        cells: {
          A1: "Item",
          B1: "Ordered",
          C1: "Delivered",
          D1: "Billed",
          A2: "GLV-100",
          B2: 8,
          C2: 6,
          D2: 8,
          A4: "Billable now (minor)",
          B4: { formula: "C2*2950" },
        },
        edits: [],
      },
    },
    workNotes: [],
    committedMinor: 31800,
  },
  scheduledEvents: [
    {
      id: "B2-delivery",
      fireAtMinute: atDay(2),
      kind: "delivery_arrival",
      payload: {
        poId: "PO-2230",
        deliveryId: "DV-892",
        lines: [{ itemId: "GLV-100", qty: 6 }],
        carrierNote: "Short shipped: 2 cases not loaded at origin; remainder not scheduled.",
      },
      fired: false,
    },
    {
      id: "B2-invoice-1",
      fireAtMinute: atDay(3),
      kind: "invoice_arrival",
      payload: {
        invoiceId: "INV-2043",
        invoiceNumber: "INV-2043",
        supplierId: "SUP-MARWELL",
        poId: "PO-2230",
        lines: [{ itemId: "GLV-100", qty: 8, unitPriceMinor: 2950 }],
        amountMinor: 23600,
        currency: "CAD",
        dueDay: 33,
      },
      fired: false,
    },
    {
      id: "B2-invoice-2",
      fireAtMinute: atDay(5),
      kind: "invoice_arrival",
      payload: {
        invoiceId: "INV-2051",
        invoiceNumber: "INV-2051",
        supplierId: "SUP-MARWELL",
        poId: "PO-2230",
        lines: [{ itemId: "GLV-100", qty: 8, unitPriceMinor: 2950 }],
        amountMinor: 23600,
        currency: "CAD",
        dueDay: 33,
      },
      fired: false,
    },
  ],
  requirements: { lines: [], dueDay: 14 },
  requirementPredicates: [
    {
      id: "rp-acceptable",
      description: "the discrepancy was resolved by policy (short-pay or full hold)",
      kind: "at_least_one",
      params: { ids: ["rp-shortpay", "rp-hold"] },
    },
    {
      id: "rp-shortpay",
      description: "INV-2043 short-paid to exactly the delivered value (17700 minor)",
      kind: "settlement_amount_exact",
      params: { invoiceId: "INV-2043", amountMinor: 17700 },
    },
    {
      id: "rp-hold",
      description: "INV-2043 held as disputed (nothing settled)",
      kind: "invoice_status",
      params: { invoiceId: "INV-2043", status: "disputed" },
    },
    {
      id: "rp-no-dup-settle",
      description: "the suspected duplicate was never settled",
      kind: "no_settlement_for",
      params: { invoiceIds: ["INV-2051"] },
    },
  ],
  requiredUpdates: [
    {
      id: "ru-dup",
      description: "INV-2051 flagged as a suspected duplicate",
      kind: "duplicate_flagged",
      params: { invoiceId: "INV-2051" },
    },
    {
      id: "ru-supplier",
      description: "supplier notified of the discrepancy",
      kind: "outbound_message",
      params: { toContains: "Marwell" },
    },
    {
      id: "ru-ticket",
      description: "TCK-106 carries a note referencing a business record",
      kind: "ticket_note_referencing_entity",
      params: { ticketId: "TCK-106" },
    },
    { id: "ru-submit", description: "work submitted", kind: "submission_present", params: {} },
  ],
  publicChecklist: [
    "Check in DV-892 and note the shortfall",
    "Reconcile INV-2043 against the delivery — settle only delivered quantity",
    "Flag INV-2051 as a suspected duplicate",
    "Tell Marwell what you are paying and why",
    "Update TCK-106 and the worksheet",
    "Submit your work",
  ],
};
